Correct preprocessor directive syntax
The previous incorrect syntax cause compilation of the library to fail:

SparkFun_CCS811_Arduino_Library\src\SparkFunCCS811.cpp:61:8: error: macro names must be identifiers

 #ifdef (ARDUINO_ARCH_ESP32 ARDUINO_ARCH_ESP8266)

        ^

Note that compilation for ESP32 still fails with a different error:

SparkFun_CCS811_Arduino_Library\src\SparkFunCCS811.cpp:62:7: error: 'class TwoWire' has no member named 'setClockStretchLimit'

  Wire.setClockStretchLimit(200000);// was defautl 230 uS, now 200ms

       ^

From https://github.com/espressif/arduino-esp32/issues/81, it's not clear whether there are plans to ever add the setClockStretchLimit function for ESP32.